image_name1:
    image_filepath: "../input_data/ZM131_5B_136_roi_0.ome.tif"
    roi_filepath: "../input_data/ZM131_5B_136_roi_0.ome.tif-1105078-rois.csv"
    markers_filepath: "../input_data/markers.csv"
