image_name1:
  image_filepath: /path/to/image.ome.tif
  markers_filepath: /path/to/markers.csv
  mask_cell:
    filepath: /path/to/cellRingOutlines.tif
  mask_nuclei:
    filepath: /path/to/nucleiRingOutlines.tif
  roi_filepath: /path/to/roi_list.csv
